# Generated by Django 3.1.8 on 2021-06-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0003_banktransaction_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='json_data',
            field=models.CharField(blank=True, max_length=64 * 1024 * 3),
        ),
    ]
