# Generated by Django 3.1 on 2020-08-31 21:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('patient_id', models.UUIDField(editable=False, primary_key=True, serialize=True)),
                ('encrypted_symmetric_key', models.UUIDField(editable=False, serialize=True)),
            ],
            options={
                'default_related_name': 'keys',
            },
        ),
    ]
